version: '3.6'

services:
  django_bot:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: django_bot
    tty: true
    restart: always
    volumes:
      - ./:/src
    env_file:
      - db_keys.txt
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - mynetwork
    command: sh -c "python3 manage.py migrate
               && python3 manage.py runserver 0.0.0.0:8000"

  bot:
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    container_name: greenbot
    restart: always
    volumes:
      - ./:/src
    env_file:
      - db_keys.txt
    depends_on:
      - db
    expose:
      - 8000
    networks:
      - mynetwork
    command: sh -c "python3 bot/mybot.py"

  db:
    image: postgres
    container_name: postgres
    restart: always
    env_file:
      - db_keys.txt
    ports:
    - 5432:5432
    networks:
      - mynetwork

  adminer:
    image: adminer
    container_name: admin_db
    restart: on-failure
    ports:
    - 8080:8080
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
